name = "corecpp"
defaultTargets = ["CoreCpp", "corecpp", "Preproc", "ccpp-pre"]

[[require]]
name = "ll1"
git = "https://github.com/ChristianoBraga/ll1-lean"
rev = "main"

[[lean_lib]]
name = "CoreCpp"

[[lean_exe]]
name = "corecpp"
root = "Main"

[[lean_exe]]
name = "ebnf2lean"
srcDir = "tools"
root = "Ebnf2Lean"

[[lean_lib]]
name = "Preproc"
srcDir = "preproc"

[[lean_exe]]
name = "ccpp-pre"
srcDir = "preproc"
root = "PreprocMain"
