(* The expression grammar of Hovemeyer, Lecture 9, LL(1) parsing, Johns Hopkins 601.428/628, *)
(* 2022, https://jhucompilers.github.io/fall2022/lectures/lecture09-public.pdf, with its *)
(* productions numbered 1 to 10. The nonterminals E' and T' of the lecture are Eprime and Tprime. *)

E = T Eprime ;
Eprime = "+" T Eprime
       | "-" T Eprime
       |
       ;
T = F Tprime ;
Tprime = "*" F Tprime
       | "/" F Tprime
       |
       ;
F = "i"
  | "n"
  ;
