(* Oberon-0, Wirth, Compiler Construction, revised edition of May 2017, chapter 6, p. 30, *)
(* https://people.inf.ethz.ch/wirth/CompilerConstruction/CompilerConstruction1.pdf *)
(* The lexical rules ident, integer and number are the token classes ident and number. *)
(* RepeatStatement is defined on the page and unused by statement, as there. *)
(* The start symbol is module. *)

selector = { ( "." ident | "[" expression "]" ) } ;
factor = ident selector
       | number
       | "(" expression ")"
       | "~" factor
       ;
term = factor { ( "*" | "DIV" | "MOD" | "&" ) factor } ;
SimpleExpression = [ ( "+" | "-" ) ] term { ( "+" | "-" | "OR" ) term } ;
expression = SimpleExpression [ ( "=" | "#" | "<" | "<=" | ">" | ">=" ) SimpleExpression ] ;
assignment = ident selector ":=" expression ;
ActualParameters = "(" [ expression { "," expression } ] ")" ;
ProcedureCall = ident selector [ ActualParameters ] ;
IfStatement = "IF" expression "THEN" StatementSequence { "ELSIF" expression "THEN" StatementSequence } [ "ELSE" StatementSequence ] "END" ;
WhileStatement = "WHILE" expression "DO" StatementSequence "END" ;
RepeatStatement = "REPEAT" StatementSequence "UNTIL" expression ;
statement = [ ( assignment | ProcedureCall | IfStatement | WhileStatement ) ] ;
StatementSequence = statement { ";" statement } ;
IdentList = ident { "," ident } ;
ArrayType = "ARRAY" expression "OF" type ;
FieldList = [ IdentList ":" type ] ;
RecordType = "RECORD" FieldList { ";" FieldList } "END" ;
type = ident
     | ArrayType
     | RecordType
     ;
FPSection = [ "VAR" ] IdentList ":" type ;
FormalParameters = "(" [ FPSection { ";" FPSection } ] ")" ;
ProcedureHeading = "PROCEDURE" ident [ FormalParameters ] ;
ProcedureBody = declarations [ "BEGIN" StatementSequence ] "END" ident ;
ProcedureDeclaration = ProcedureHeading ";" ProcedureBody ;
declarations = [ "CONST" { ident "=" expression ";" } ] [ "TYPE" { ident "=" type ";" } ] [ "VAR" { IdentList ":" type ";" } ] { ProcedureDeclaration ";" } ;
module = "MODULE" ident ";" declarations [ "BEGIN" StatementSequence ] "END" ident "." ;
