import CoreCpp.Token
import CoreCpp.LL1

/-!
# Terminals of the grammar of Core C++

The token classes of the grammar of Core C++, their reading from the EBNF
file `grammar/core-cpp.ebnf`, and the printing of the rules as the Lean
module `CoreCpp/GrammarRules.lean`. In the file, `TypeId`, `VarId` and
`IntLit` are token classes. A quoted literal with a letter is a reserved word,
and any other quoted literal is a symbol.
-/

namespace CoreCpp.Grammar

open CoreCpp.LL1

/-- A terminal of the grammar, a token class. Reserved words and symbols stand
for themselves, identifiers and literals for their class. -/
inductive Term where
  | kw (s : String)
  | sym (s : String)
  | typeId
  | varId
  | intLit
  deriving Repr, BEq, DecidableEq, Hashable

/-- The class of a token. The end token maps to a symbol that the grammar
lacks. `derive` drops that token, and the parser reads the end marker from
the end of the list. -/
def Term.ofToken : Token → Term
  | .kw s => .kw s
  | .sym s => .sym s
  | .typeId _ => .typeId
  | .varId _ => .varId
  | .intLit _ => .intLit
  | .eof => .sym "<eof>"

/-- The token classes of the EBNF file. -/
def classes : List String := ["TypeId", "VarId", "IntLit"]

/-- The terminal of a terminal of the EBNF file. -/
def Term.ofString (a : String) : Term :=
  if a == "TypeId" then .typeId
  else if a == "VarId" then .varId
  else if a == "IntLit" then .intLit
  else if a.any Char.isAlpha then .kw a
  else .sym a

/-- The terminal of the EBNF file of a terminal. -/
def Term.toStr : Term → String
  | .kw s | .sym s => s
  | .typeId => "TypeId"
  | .varId => "VarId"
  | .intLit => "IntLit"

mutual

def Ebnf.map (f : α → β) : Ebnf α → Ebnf β
  | .t a => .t (f a)
  | .n A => .n A
  | .seq es => .seq (Ebnf.mapAll f es)
  | .alt es => .alt (Ebnf.mapAll f es)
  | .star e => .star (Ebnf.map f e)
  | .opt e => .opt (Ebnf.map f e)

def Ebnf.mapAll (f : α → β) : List (Ebnf α) → List (Ebnf β)
  | [] => []
  | e :: es => Ebnf.map f e :: Ebnf.mapAll f es

end

/-- The rules of the EBNF file over the terminals of Core C++. -/
def ofEbnf (rs : List (Rule String)) : List (Rule Term) :=
  rs.map fun r => ⟨r.lhs, Ebnf.map Term.ofString r.rhs⟩

/-- The rules over the terminals of the EBNF file. -/
def toEbnf (rs : List (Rule Term)) : List (Rule String) :=
  rs.map fun r => ⟨r.lhs, Ebnf.map Term.toStr r.rhs⟩

/-! ## Printing as Lean -/

def leanTerm : Term → String
  | .kw s => s!"(.kw {s.quote})"
  | .sym s => s!"(.sym {s.quote})"
  | .typeId => ".typeId"
  | .varId => ".varId"
  | .intLit => ".intLit"

mutual

/-- A Lean term for an EBNF expression. -/
def leanOf : Ebnf Term → String
  | .t a => s!".t {leanTerm a}"
  | .n A => s!".n {A.quote}"
  | .seq es => s!".seq [{", ".intercalate (leanOfAll es)}]"
  | .alt es => s!".alt [{", ".intercalate (leanOfAll es)}]"
  | .star e => s!".star ({leanOf e})"
  | .opt e => s!".opt ({leanOf e})"

def leanOfAll : List (Ebnf Term) → List String
  | [] => []
  | e :: es => leanOf e :: leanOfAll es

end

/-- The Lean module that defines `CoreCpp.Grammar.rules`. -/
def leanModule (source : String) (rs : List (Rule Term)) : String :=
  let items := rs.map fun r => s!"  ⟨{r.lhs.quote}, {leanOf r.rhs}⟩"
  s!"-- Generated by `lake exe ebnf2lean` from `{source}`. Do not edit.\n" ++
  "import CoreCpp.GrammarTerm\n\n" ++
  "namespace CoreCpp.Grammar\n\n" ++
  "open CoreCpp.LL1\n\n" ++
  s!"/-- The rules of the grammar of Core C++, generated from `{source}`. -/\n" ++
  "def rules : List (Rule Term) := [\n" ++ ",\n".intercalate items ++ "]\n\n" ++
  "end CoreCpp.Grammar\n"

end CoreCpp.Grammar
