-- Generated by `lake exe ebnf2lean` from `grammar/core-cpp.ebnf`. Do not edit.
import CoreCpp.GrammarTerm

namespace CoreCpp.Grammar

open LL1

/-- The rules of the grammar of Core C++, generated from `grammar/core-cpp.ebnf`. -/
def rules : List (Rule Term) := [
  ⟨"Program", .star (.n "Declaration")⟩,
  ⟨"Declaration", .alt [.seq [.t (.kw "namespace"), .n "Name", .t (.sym "{"), .star (.n "Declaration"), .t (.sym "}")], .seq [.t (.kw "template"), .t (.sym "<"), .t (.kw "typename"), .t .typeId, .star (.seq [.t (.sym ","), .t (.kw "typename"), .t .typeId]), .t (.sym ">"), .t (.kw "class"), .alt [.seq [.t .typeId, .n "ClassRest"], .seq [.t .varId, .t (.sym ";")]]], .n "Class", .n "Function"]⟩,
  ⟨"Name", .alt [.t .typeId, .t .varId]⟩,
  ⟨"Class", .seq [.t (.kw "class"), .t .typeId, .n "ClassRest"]⟩,
  ⟨"ClassRest", .seq [.opt (.seq [.t (.sym ":"), .t (.kw "public"), .n "ClassType"]), .t (.sym "{"), .star (.n "Member"), .star (.n "Section"), .t (.sym "}"), .t (.sym ";")]⟩,
  ⟨"Section", .seq [.alt [.t (.kw "public"), .t (.kw "private")], .t (.sym ":"), .star (.n "Member")]⟩,
  ⟨"Member", .alt [.seq [.t (.kw "virtual"), .alt [.seq [.n "Type", .opt (.t (.sym "&")), .n "MemberRest"], .seq [.t (.sym "~"), .t .typeId, .t (.sym "("), .t (.sym ")"), .n "Block"]]], .seq [.t (.sym "~"), .t .typeId, .t (.sym "("), .t (.sym ")"), .n "Block"], .seq [.alt [.n "BasicType", .seq [.t .nsId, .t (.sym "::"), .n "QualTail", .opt (.t (.sym "*"))]], .opt (.t (.sym "&")), .n "MemberRest"], .seq [.t .typeId, .alt [.seq [.n "Params", .n "Block"], .seq [.opt (.n "TemplateArgs"), .opt (.t (.sym "*")), .opt (.t (.sym "&")), .n "MemberRest"]]]]⟩,
  ⟨"MemberRest", .alt [.seq [.t .varId, .alt [.t (.sym ";"), .seq [.n "Params", .opt (.t (.kw "override")), .n "Block"]]], .seq [.t (.kw "operator"), .n "Op", .n "Params", .n "Block"]]⟩,
  ⟨"Op", .alt [.t (.sym "+"), .t (.sym "-"), .t (.sym "*"), .t (.sym "/"), .t (.sym "%"), .t (.sym "=="), .t (.sym "!="), .t (.sym "<"), .t (.sym "<="), .t (.sym ">"), .t (.sym ">="), .seq [.t (.sym "["), .t (.sym "]")]]⟩,
  ⟨"Function", .seq [.n "Type", .t .varId, .n "Params", .alt [.n "Block", .t (.sym ";")]]⟩,
  ⟨"Params", .seq [.t (.sym "("), .opt (.seq [.n "Param", .star (.seq [.t (.sym ","), .n "Param"])]), .t (.sym ")")]⟩,
  ⟨"Param", .seq [.n "Type", .opt (.t (.sym "&")), .t .varId]⟩,
  ⟨"Type", .alt [.n "BasicType", .seq [.n "ClassType", .opt (.t (.sym "*"))]]⟩,
  ⟨"TemplateArg", .seq [.n "Type", .opt (.seq [.t (.sym "("), .opt (.seq [.n "Type", .star (.seq [.t (.sym ","), .n "Type"])]), .t (.sym ")")])]⟩,
  ⟨"BasicType", .alt [.t (.kw "int"), .t (.kw "bool"), .t (.kw "void")]⟩,
  ⟨"ClassType", .alt [.seq [.t .nsId, .t (.sym "::"), .n "QualTail"], .seq [.t .typeId, .opt (.n "TemplateArgs")]]⟩,
  ⟨"QualTail", .alt [.seq [.t .nsId, .t (.sym "::"), .n "QualTail"], .seq [.n "Name", .opt (.n "TemplateArgs")]]⟩,
  ⟨"TemplateArgs", .seq [.t (.sym "<"), .n "TemplateArg", .star (.seq [.t (.sym ","), .n "TemplateArg"]), .t (.sym ">")]⟩,
  ⟨"Block", .seq [.t (.sym "{"), .star (.n "Statement"), .t (.sym "}")]⟩,
  ⟨"Statement", .alt [.n "Block", .seq [.t (.kw "if"), .t (.sym "("), .n "Expr", .t (.sym ")"), .n "Block", .opt (.seq [.t (.kw "else"), .n "Block"])], .seq [.t (.kw "while"), .t (.sym "("), .n "Expr", .t (.sym ")"), .n "Block"], .seq [.t (.kw "for"), .t (.sym "("), .n "ForInit", .t (.sym ";"), .n "Expr", .t (.sym ";"), .n "ExprStatement", .t (.sym ")"), .n "Block"], .seq [.t (.kw "return"), .opt (.n "ArgExpr"), .t (.sym ";")], .seq [.t (.kw "delete"), .n "Expr", .t (.sym ";")], .seq [.n "LocalDecl", .t (.sym ";")], .seq [.n "ExprStatement", .t (.sym ";")]]⟩,
  ⟨"LocalDecl", .alt [.seq [.t (.kw "auto"), .t .varId, .t (.sym "="), .n "Expr"], .seq [.n "Type", .opt (.t (.sym "&")), .t .varId, .t (.sym "="), .n "ArgExpr"]]⟩,
  ⟨"ForInit", .alt [.n "LocalDecl", .n "ExprStatement"]⟩,
  ⟨"ExprStatement", .seq [.n "Expr", .opt (.seq [.t (.sym "="), .n "Expr"])]⟩,
  ⟨"Expr", .seq [.n "OrExpr", .opt (.seq [.t (.sym "?"), .n "Expr", .t (.sym ":"), .n "Expr"])]⟩,
  ⟨"OrExpr", .seq [.n "AndExpr", .star (.seq [.t (.sym "||"), .n "AndExpr"])]⟩,
  ⟨"AndExpr", .seq [.n "EqExpr", .star (.seq [.t (.sym "&&"), .n "EqExpr"])]⟩,
  ⟨"EqExpr", .seq [.n "RelExpr", .star (.seq [.alt [.t (.sym "=="), .t (.sym "!=")], .n "RelExpr"])]⟩,
  ⟨"RelExpr", .seq [.n "AddExpr", .star (.seq [.alt [.t (.sym "<"), .t (.sym "<="), .t (.sym ">"), .t (.sym ">=")], .n "AddExpr"])]⟩,
  ⟨"AddExpr", .seq [.n "MulExpr", .star (.seq [.alt [.t (.sym "+"), .t (.sym "-")], .n "MulExpr"])]⟩,
  ⟨"MulExpr", .seq [.n "UnaryExpr", .star (.seq [.alt [.t (.sym "*"), .t (.sym "/"), .t (.sym "%")], .n "UnaryExpr"])]⟩,
  ⟨"UnaryExpr", .alt [.seq [.alt [.t (.sym "!"), .t (.sym "-"), .t (.sym "*")], .n "UnaryExpr"], .n "PostfixExpr"]⟩,
  ⟨"PostfixExpr", .seq [.n "Primary", .n "Chain"]⟩,
  ⟨"Chain", .opt (.alt [.seq [.t (.sym "["), .n "Expr", .t (.sym "]"), .n "Chain"], .seq [.t (.sym "."), .t .varId, .n "After"], .seq [.t (.sym "->"), .t .varId, .n "After"], .seq [.n "Args", .n "Chain"]])⟩,
  ⟨"After", .alt [.seq [.n "Args", .n "Chain"], .n "ChainNoCall"]⟩,
  ⟨"ChainNoCall", .opt (.alt [.seq [.t (.sym "["), .n "Expr", .t (.sym "]"), .n "Chain"], .seq [.t (.sym "."), .t .varId, .n "After"], .seq [.t (.sym "->"), .t .varId, .n "After"]])⟩,
  ⟨"Primary", .alt [.t .intLit, .t (.kw "true"), .t (.kw "false"), .t (.kw "nullptr"), .t (.kw "this"), .t .varId, .seq [.t (.sym "("), .n "Expr", .t (.sym ")")], .seq [.t (.kw "new"), .n "ClassType", .n "Args"]]⟩,
  ⟨"Args", .seq [.t (.sym "("), .opt (.seq [.n "ArgExpr", .star (.seq [.t (.sym ","), .n "ArgExpr"])]), .t (.sym ")")]⟩,
  ⟨"ArgExpr", .alt [.n "Lambda", .n "Expr"]⟩,
  ⟨"Lambda", .seq [.t (.sym "[=]"), .n "Params", .t (.sym "->"), .n "Type", .n "Block"]⟩]

end CoreCpp.Grammar
